import type { Config } from "tailwindcss"

const config: Config = {
    darkMode: ["class"],
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    prefix: "",
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        extend: {
            colors: {
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
            },
            textColor: {
                pristine: "#2EA996",
                "pristine-sat-40": "#03D4B4",
                "pristine-light-40": "#A5FEF0",
                "pristine-grey": "#F3F5F4",
                "pristine-light-grey": "#F3F7F9",
                "red-100": "#FDE9EF",
                red: "#C71822",
                "accent-red": "#F44437",
                yellow: "#FFD84D",
                "yellow-darken": "#DFA100",
                "white-darken-15": "#D9D9D9",
                "white-darken-30": "#909090",
                "light-grey": "#C4C4C4",
                "ultra-light-grey": "#ECECEC",
                "grey-darken": "#1E1E1E",
                "grey-darken-30": "#474747",
                "grey-darken-40": "#454545",
                blue: "#5DBCF9",
                "blueGrey-light": "#F3F7F9",
                "blue-ocean-100": "#E9F5FE",
                "blue-ocean": "#0772B6",
                "blue-deep-ocean": "#04446C",
                green: "#4DAF51",
                "green-darker": "#00A645",
                pink: "#FFC6C9",
                purple: "#BB6BD9",
                disabled: "#F3F5F4",
                success: "#4DAF51",
                error: "#F44437",
                info: "#2296F3",
                warning: "#FFB301",
            },
            backgroundColor: {
                pristine: "#2EA996",
                "pristine-sat-40": "#03D4B4",
                "pristine-light-40": "#A5FEF0",
                "pristine-grey": "#F3F5F4",
                "pristine-light-grey": "#F3F7F9",
                "red-100": "#FDE9EF",
                red: "#C71822",
                "accent-red": "#F44437",
                yellow: "#FFD84D",
                "yellow-darken": "#DFA100",
                "white-darken-15": "#D9D9D9",
                "white-darken-30": "#909090",
                "light-grey": "#C4C4C4",
                "ultra-light-grey": "#ECECEC",
                "grey-darken": "#1E1E1E",
                "grey-darken-30": "#474747",
                "grey-darken-40": "#454545",
                blue: "#5DBCF9",
                "blueGrey-light": "#F3F7F9",
                "blue-ocean-100": "#E9F5FE",
                "blue-ocean": "#0772B6",
                "blue-deep-ocean": "#04446C",
                green: "#4DAF51",
                "green-darker": "#00A645",
                pink: "#FFC6C9",
                purple: "#BB6BD9",
                disabled: "#F3F5F4",
                success: "#4DAF51",
                error: "#F44437",
                info: "#2296F3",
                warning: "#FFB301",
            },
            backgroundImage: {
                "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
                "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
                "linear-gradient-blue-ocean": "linear-gradient(180deg, rgba(7, 114, 182, 0.25) 0%, #0772B6 100%)",
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
                "small-5px": "5px",
                "medium-12px": "12px",
                "large-45px": "45px",
            },
            borderColor: {
                pristine: "#2EA996",
                "pristine-sat-40": "#03D4B4",
                "pristine-light-40": "#A5FEF0",
                "pristine-grey": "#F3F5F4",
                "pristine-light-grey": "#F3F7F9",
                "red-100": "#FDE9EF",
                red: "#C71822",
                "accent-red": "#F44437",
                yellow: "#FFD84D",
                "yellow-darken": "#DFA100",
                "white-darken-15": "#D9D9D9",
                "white-darken-30": "#909090",
                "light-grey": "#C4C4C4",
                "ultra-light-grey": "#ECECEC",
                "grey-darken": "#1E1E1E",
                "grey-darken-30": "#474747",
                "grey-darken-40": "#454545",
                blue: "#5DBCF9",
                "blueGrey-light": "#F3F7F9",
                "blue-ocean-100": "#E9F5FE",
                "blue-ocean": "#0772B6",
                "blue-deep-ocean": "#04446C",
                green: "#4DAF51",
                "green-darker": "#00A645",
                pink: "#FFC6C9",
                purple: "#BB6BD9",
                disabled: "#F3F5F4",
                success: "#4DAF51",
                error: "#F44437",
                info: "#2296F3",
                warning: "#FFB301",
            },
            boxShadow: {
                "auction-sm": "0px 32px 100px 0px rgba(0, 0, 0, 0.08)",
                "auction-md": "0px 0px 5px 0px rgba(0, 0, 0, 0.25)",
            },
            keyframes: {
                "accordion-down": {
                    from: { height: "0" },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: "0" },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
} satisfies Config
export default config
